### ISSUE TITLE
Copyright notice, license

### ISSUE THREAD

**Issue by klei1984** [yaminov/svdconv#1]
Dear @yaminov , I would like to use the script if possible, but based on GitHub's terms of service in its current form the script cannot be used by anybody else but the author as you did not grant the rights to others.

Could you please take a look on GitHub's short guideline on the matter? It takes just 5 minutes: https://choosealicense.com/no-permission/

Thanks in advance for your kind support.

**Comment by yaminov** [comment]
@klei1984
added MIT license

**Comment by klei1984** [comment]
@yaminov , thanks a lot!
